README.md

add a badge to Readme.
the channel to link to is `vaadin-flow/Lobby`
issue: https://github.com/vaadin/flow/issues/2566
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/35)

Add badge to Readme

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/36)

Update version to 1.0.0.alpha4

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/38)

Update version to 1.0.0.alpha5

---

src/main/java/com/vaadin/flow/demo/helloworld/ExampleTemplate.java
src/main/java/com/vaadin/flow/demo/helloworld/MainView.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/41)

Remove explicit frontend protocol usage

---

.gitignore

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/42)

Ignore standard Eclipse files

---

pom.xml
src/main/webapp/frontend/ExampleTemplate.html
src/main/webapp/frontend/bower.json
src/main/webapp/frontend/index.html
src/main/webapp/frontend/package-lock.json
src/main/webapp/frontend/package.json
src/main/webapp/frontend/styles.html

Use webjars.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/43)

Update to newest flow version.

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/44)

Update version to 1.0.0.alpha7

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/46)

Update to newer flow version.

---

pom.xml
src/main/java/com/vaadin/flow/demo/helloworld/Servlet.java

Update to Flow alpha11 and vaadin alpha8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/50)

Update to alpha11

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/52)

Add missing Valo theme, use publicly available plugin version.

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/53)

Update flow-maven-plugin version.

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/54)

Update to version 1.0.0.alpha12

---

pom.xml
src/main/java/com/vaadin/flow/demo/helloworld/MainView.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/55)

Better spacing

---

src/main/java/com/vaadin/starter/skeleton/ExampleTemplate.java
src/main/java/com/vaadin/starter/skeleton/MainView.java
src/main/java/com/vaadin/starter/skeleton/Servlet.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/56)

Move all starters to same package

---

pom.xml
src/main/java/com/vaadin/starter/skeleton/ExampleTemplate.java
src/main/java/com/vaadin/starter/skeleton/MainView.java
src/main/java/com/vaadin/starter/skeleton/Servlet.java
src/main/resources/log4j.properties

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/58)

Update platform version

---

src/main/java/com/vaadin/starter/skeleton/MainView.java
src/main/webapp/frontend/styles.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/60)

apply-bodysize

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/64)

Set logging dependency

---

pom.xml
src/main/java/com/vaadin/starter/skeleton/MainView.java
src/main/webapp/frontend/styles.html

Note this PR requires a new Vaadin10 release to compile.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/62)

Add lumo theme to starter

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/66)

remove unnecessary repository from POM

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/68)

Update plugin version.

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/71)

Update platform version.

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/72)

Update to never platform and plugin.

---

src/main/webapp/frontend/styles/shared-styles.html

Fixes #70
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/73)

Use padding instead of margin

---

src/main/webapp/frontend/styles/shared-styles.html

Fixes #54
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/76)

Correct styles

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/77)

Update platform version to beta3

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/79)

Update platform version to beta5

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/82)

Add directory repository to pom

---

pom.xml
src/main/java/com/vaadin/starter/skeleton/MainView.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/80)

Removed the @Theme declaration

---

pom.xml
src/main/java/com/vaadin/starter/skeleton/MainView.java

DON'T MERGE until this project is depending on Flow version where https://github.com/vaadin/flow/pull/3821 is included. After that the full body size is applied by default and the annotation is not needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/81)

Remove @BodySize

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/84)

Update platform version to beta8

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/88)

Update platform dependency to Beta9

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/90)

Use vaadin-maven-plugin

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/95)

Update platform dependency to RC2

---

pom.xml

Update jetty version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/96)

Update platform to RC 3

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/97)

Update platform to RC5

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/99)

Update Platform to 10.0.1

---

.travis.yml
src/main/webapp/frontend/src/README
src/main/webapp/frontend/styles/README

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/105)

Clarify readme v11

---

src/main/java/com/vaadin/starter/skeleton/MainView.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/109)

adds missing route string, fixes #107

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/115)

Add V12 to master branch readme

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/134)

Update vaadin version to 13

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/135)

Fix branches names in readme

---

.travis.yml
pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/136)

Pin Vaadin Platform + remove snapshot and central repo

---

src/main/webapp/frontend/styles/README

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/144)

Fix link to point to latest

---

.gitignore
pom.xml

Related to https://github.com/vaadin/beverage-starter-flow/issues/332
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/152)

Update the starter to newer plugin version

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/150)

Use only one frontend node goal.

---

pom.xml

This has already been done in master as a part of another commit..
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/161)

Update jetty version for V13

---

package-lock.json
package.json
pom.xml
webpack.config.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/171)

Update files for Vaadin 14 beta 2

---

webpack.config.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/172)

Rename the goal used in webpack.config.js

---

pom.xml

Part of https://github.com/vaadin/flow/issues/5785
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/178)

Add Java 11 profile

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/179)

Use 11 release for Java11

---

pom.xml

Cherry-pick for `v13`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/180)

Added back `scanIntervalSeconds`

---

pom.xml

(cherry picked from commit 2eb96a1bad94943d37fb1ffc9bd4a4ea0e5f8c29)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/181)

Added back `scanIntervalSeconds` (#180)

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/183)

Jetty: removed systemProperties, moved stopXXX configs under IT profile

---

drivers.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/185)

Update to Chromedriver 75.0.3770.8 (#184)

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/191)

Fix tutorial link in readme

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/193)

Jetty: scaninterval of 2s and bump version

---

package-lock.json
package.json

Previous `"@polymer/polymer": "^3.1.0"` is known to cause issues
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/200)

Update npm files as recommended in release notes

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/202)

Add an instruction for running app in production mode

---

README.md
pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/205)

Polish readme

---

pom.xml

remove unnecessary repository settings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/223)

Use 1.0-SNAPSHOT for starters

---

drivers.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/224)

Update ChromeDriver version

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/237)

Add Maven central repository as the first

---

src/test/java/com/vaadin/starter/skeleton/MainViewIT.java

Fixes vaadin/platform#921
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/246)

Add usage statistics test

---

src/test/java/com/vaadin/starter/skeleton/MainViewIT.java

As the test package is going to Vcom and the user can download those, let us remove it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/255)

Remove the statistic test from starter

---

src/test/java/com/vaadin/starter/skeleton/AbstractViewTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/263)

fix link to TestBench

---

frontend/styles/shared-styles.css
frontend/styles/vaadin-text-field-styles.css
src/main/java/com/vaadin/starter/skeleton/GreetService.java
src/main/java/com/vaadin/starter/skeleton/MainView.java

Fix part of https://app.zenhub.com/workspaces/90min-dx-5d9f221dac250d00016660ff/issues/vaadin/90min-dx-tasks/62
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/274)

Upgrade the skeleton starter flow project

---

src/main/java/org/vaadin/example/GreetService.java
src/main/java/org/vaadin/example/MainView.java
src/test/java/org/vaadin/example/AbstractViewTest.java
src/test/java/org/vaadin/example/MainViewIT.java

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/285)

Picks from master to V14

---

src/test/java/org/vaadin/example/MainViewIT.java

(cherry picked from commit 8e2d84aa29d93c8ac371be8f81d31767f5b0a099)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/298)

Create new set of tests for new starter code (#297)

---

pom.xml

Related to https://github.com/vaadin/flow/issues/7822
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/306)

Upgrade the Jetty Maven plugin

---

pom.xml

Related to vaadin/flow#7822
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/308)

Upgrade the Jetty Maven plugin in v14

---

src/main/java/org/vaadin/example/AppShell.java
src/main/java/org/vaadin/example/MainView.java

Fix https://github.com/vaadin/skeleton-starter-flow/issues/307
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/309)

Fix PWA error by adding AppShell in skeleton starter flow

---

src/main/java/org/vaadin/example/AppShell.java

Fixes #311
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/317)

Fix PWA name value to not say Spring

---

src/main/java/org/vaadin/example/MainView.java

Related to https://github.com/vaadin/flow/issues/8038
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/321)

Do not show install prompt : V14

---

pom.xml

Fix vaadin/90min-dx-tasks#160
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/330)

Upgrade Jetty version for V15

---

pom.xml

Fix vaadin/90min-dx-tasks#160
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/329)

Upgrade Jetty version for V14

---

README.md

Fixes https://github.com/vaadin/90min-dx-tasks/issues/164
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/333)

Add info for running tests to ReadMe

---

README.md
pom.xml

Fixes: https://github.com/vaadin/90min-dx-tasks/issues/174
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/337)

Change it name in ReadMe and pom.xml

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/346)

Add running integration tests section

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/347)

Add section about integration tests

---

frontend/styles/vaadin-text-field-styles.css
src/main/java/org/vaadin/example/MainView.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/350)

Scope custom text field styling to a single instance

---

frontend/styles/vaadin-text-field-styles.css
src/main/java/org/vaadin/example/MainView.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/349)

Master : Scope custom text field styling to a single instance

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/365)

Add comment to plugin repo definition

---

.gitpod.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/380)

adds gitpod config file

---

.gitpod.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/379)

Adds gitpod config for LTS branch

---

.gitpod.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/382)

fixes gitpod instructions in master

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/384)

sets beta version

---

package-lock.json
package.json
pom.xml

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.
Fixes # (issue)

Update to Vaadin 14.6.3

---

pom.xml

Bump webdrivermanager to 5.0.3 (vLatest)
